- .circleci/config.yml
- friendly_shipping.gemspec
- lib/friendly_shipping/label.rb
- lib/friendly_shipping/services/ship_engine/parse_label_response.rb
- spec/fixtures/ship_engine/labels_success.json
- spec/friendly_shipping/services/ship_engine/parse_label_response_spec.rb
- spec/friendly_shipping/services/ship_engine_spec.rb
- spec/spec_helper.rb
This is more of a convenience method. Technically we could get that out
of the URL or out of the `data` hash, but we really should be using the
dedicated field from the API.
> Add Label Format to Physical Label object

- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
As ShipEngine is a meta-Shipping provider, they allow specifying a
carrier ID in their request. This PR enables passing the carrier ID as
part of the Physical::Shipment options hash.
> Allow specifying a carrier ID from calling code

- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
The `package` package code is not binding. Let's omit it unless the
calling code specifies a package code.
> Do not send package code when not necessary

- friendly_shipping.gemspec
- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
- lib/friendly_shipping/version.rb
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
This updates the `physical` dependency to version 0.2. Physical's API changes are mostly in package construction, not in package consumption, so the changes are almost exclusively in our specs.
> Physical 0.2

- friendly_shipping.gemspec
- lib/friendly_shipping/version.rb
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
Physical in version 0.3 does not sort the dimensions of cuboids any
longer and thus will keep their order, which makes for much more
predictable code. This is in line with the behaviour of Physical 0.1.
> Updates Physical usage to 0.3

- lib/friendly_shipping/rest_client.rb
- lib/friendly_shipping/services/ship_engine.rb
- lib/friendly_shipping/services/ship_engine/parse_void_response.rb
- lib/friendly_shipping/version.rb
- spec/friendly_shipping/rest_client_spec.rb
- spec/friendly_shipping/services/ship_engine/parse_void_response_spec.rb
- spec/friendly_shipping/services/ship_engine_spec.rb
This implements the 'void' call to ShipEngine. It's structurally a
little bit different to the other calls, mostly because errors look
slightly different as in the other calls.
> Implement ShipEngine 'void' call

- friendly_shipping.gemspec
- lib/friendly_shipping.rb
- lib/friendly_shipping/rate.rb
- lib/friendly_shipping/services/ship_engine.rb
- lib/friendly_shipping/services/ship_engine/parse_carrier_response.rb
- lib/friendly_shipping/services/ship_engine/parse_rate_estimate_response.rb
- lib/friendly_shipping/services/ship_engine/serialize_rate_estimate_request.rb
- lib/friendly_shipping/shipping_method.rb
- spec/cassettes/shipengine/rate_estimates/success.yml
- spec/fixtures/ship_engine/rate_estimates_success.json
- spec/friendly_shipping/rate_spec.rb
- spec/friendly_shipping/services/ship_engine/parse_rate_estimate_response_spec.rb
- spec/friendly_shipping/services/ship_engine/serialize_rate_estimate_request_spec.rb
- spec/friendly_shipping/services/ship_engine_spec.rb
This adds a `FriendlyShipping::Rate` object and support for estimating rates through ShipEngine. These rates, as they are estimates, do not have a `rate_id`. There is another endpoint that persists the estimates on ShipEngine's sind, and the rate object and possible the parser should be able to handle that as well.
> Add Rate estimating

- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
Max weight for USPS First Class packages is 15.9 oz, not 16 oz as would be expected. When generating a First Class shipping label, Ship Engine rejects all packages heavier than 15.9 oz.
Whenever we have a package that is close to or exactly 1 lb (for example, 15.91 oz) we should still be able to ship that package First Class. This change ensures Ship Engine won't reject creating the label due to the package being considered too heavy.
> Allow 1 lb packages to qualify for USPS First Class labels

- friendly_shipping.gemspec
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
- spec/friendly_shipping/services/ship_engine/serialize_rate_estimate_request_spec.rb
Physical changed its box factory to be a more plausible shipping box
in db56257cb815ef5411acdadfc4fa4354e5072630 and now accepts
`void_fill_density` in `Measured::Density` only.
> Use at least physical 0.4.0

- lib/friendly_shipping.rb
- lib/friendly_shipping/services/usps.rb
- lib/friendly_shipping/services/usps/choose_package_rate.rb
- lib/friendly_shipping/services/usps/client.rb
- lib/friendly_shipping/services/usps/machinable_package.rb
- lib/friendly_shipping/services/usps/parse_package_rate.rb
- lib/friendly_shipping/services/usps/parse_rate.rb
- lib/friendly_shipping/services/usps/parse_rate_response.rb
- lib/friendly_shipping/services/usps/parse_xml_response.rb
- lib/friendly_shipping/services/usps/serialize_rate_request.rb
- lib/friendly_shipping/services/usps/shipping_methods.rb
- spec/cassettes/usps/rate_estimates/failure.yml
- spec/cassettes/usps/rate_estimates/success.yml
- spec/fixtures/usps/rates_api_response_large_box.xml
- spec/fixtures/usps/rates_api_response_regional_multiple.xml
- spec/fixtures/usps/rates_api_response_regional_single.xml
- spec/fixtures/usps/usps_rates_api_response.xml
- spec/friendly_shipping/services/usps/choose_package_rate_spec.rb
- spec/friendly_shipping/services/usps/machinable_package_spec.rb
- spec/friendly_shipping/services/usps/parse_package_rate_spec.rb
- spec/friendly_shipping/services/usps/parse_rate_response_spec.rb
- spec/friendly_shipping/services/usps/parse_rate_spec.rb
- spec/friendly_shipping/services/usps/parse_xml_response_spec.rb
- spec/friendly_shipping/services/usps/serialize_rate_request_spec.rb
- spec/friendly_shipping/services/usps_spec.rb
- spec/spec_helper.rb
This adds the capability of estimating USPS rates directly from USPS.
There is pretty complicated code, because the USPS rating API has a lot
of functionality and an interesting data model.
When requesting rates for a shipment, USPS will return all possible
rates for each package. This means that we need to match the response's
rates to each of the packages, and then sum the rates for all the
packages to get rates for the entire shipment.
Compared to previous API implementations, we're using USPS' endpoint
with POST requests rather than GET requests because that makes VCR
cassette matching easier and probably also allows longer a longer
request payload.
> Add USPS rate estimation endpoint

- lib/friendly_shipping/version.rb
- spec/friendly_shipping/services/usps/serialize_rate_request_spec.rb
Physical 0.4 changes how `Physical::Packages` `void_fill_weight` is initialized. This PR incorporates this change in the USPS serializer spec and bumps the version again so the latest `friendly_shipping` gem actually has a passing build.
> Update USPS specs for Physical 0.4

- lib/friendly_shipping.rb
- lib/friendly_shipping/address_validation_result.rb
- lib/friendly_shipping/services/ups.rb
- lib/friendly_shipping/services/ups/parse_address_validation_response.rb
- lib/friendly_shipping/services/ups/parse_city_state_lookup_response.rb
- lib/friendly_shipping/services/ups/serialize_address_validation_request.rb
- lib/friendly_shipping/services/ups/serialize_city_state_lookup_request.rb
- spec/cassettes/ups/address_validation/correctable_address.yml
- spec/cassettes/ups/address_validation/incomplete_address.yml
- spec/cassettes/ups/address_validation/invalid_address.yml
- spec/cassettes/ups/address_validation/valid_address.yml
- spec/cassettes/ups/city_state_lookup/failure.yml
- spec/cassettes/ups/city_state_lookup/multiple_states.yml
- spec/cassettes/ups/city_state_lookup/success.yml
- spec/fixtures/ups/address_validation_no_candidates_response.xml
- spec/fixtures/ups/address_validation_response.xml
- spec/fixtures/ups/city_state_lookup_response.xml
- spec/friendly_shipping/address_validation_result_spec.rb
- spec/friendly_shipping/services/ups/parse_address_validation_response_spec.rb
- spec/friendly_shipping/services/ups/parse_city_state_lookup_response_spec.rb
- spec/friendly_shipping/services/ups/serialize_address_snippet_spec.rb
- spec/friendly_shipping/services/ups/serialize_address_validation_request_spec.rb
- spec/friendly_shipping/services/ups/serialize_city_state_lookup_request_spec.rb
- spec/friendly_shipping/services/ups_spec.rb
This adds support for UPS' address validation endpoint.
The API is still experimental. I would like to also support ambiguous addresses (where UPS returns multiple candidates), but I do not know a CA or NY address that would be ambiguous for testing. @pelargir do you have an address that we could use for that, or know how to mangle that of the UN building so it becomes ambiguous? 
In that case we should probably wrap an Array of addresses into the `Success` we return. For consistency, we should then also wrap the single address returned for unambiguous addresses into an Array. What do you think?
> Add support for UPS Address Validation (XAV) endpoint 

- lib/friendly_shipping/services/ups/serialize_address_snippet.rb
- spec/friendly_shipping/services/ups/serialize_address_snippet_spec.rb
Previously, the UPS API would return a commercial rate if the
destination address was commercial, even if the residential flag was
included in the API call. That appears to no longer be the case. Now,
UPS will sometimes return a commercial rate if it knows the address
is commercial, but other times it won't. Therefore, we need to
conditionally include the residential flag based on the address type.
Co-Authored-By: Matthew Bass <matt@candlescience.com>
> Do not mark commercial addresses as residential for UPS

- README.md
- lib/friendly_shipping/services/ship_engine.rb
- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
- spec/friendly_shipping/services/ship_engine_spec.rb
When generating a label, at the time we generate it the shipping method
service code is not a property of the shipment (yet). I believe this is
a clearer API that reads better: Having a shipment, and then specifying
explicitly which shipping method to use. Bonus: That shipping method has
a `carrier` property which we can use rather than adding yet another
optional string.
> Extract shipping method to separate argument in labels API

- README.md
- lib/friendly_shipping/services/ups.rb
- lib/friendly_shipping/services/ups/parse_address_classification_response.rb
- spec/fixtures/ups/address_validation_ambiguous_address_response.xml
- spec/friendly_shipping/services/ups/parse_address_classification_response_spec.rb
This new endpoint returns just the address classification from the XAV endpoint. No validation information is returned. This is necessary because the address validation endpoint returns a failure when no address candidates are found (or when an ambiguous address is used), but the UPS API will often return an address classification even when there are no candidates (or an ambiguous address). We need the ability to retrieve and use the address classification in these situations.
> Add Ups#address_classification API endpoint

- .gitignore
- lib/friendly_shipping/services/ups/serialize_address_validation_request.rb
- spec/cassettes/ups/address_validation/correctable_address.yml
- spec/cassettes/ups/address_validation/incomplete_address.yml
- spec/cassettes/ups/address_validation/invalid_address.yml
- spec/cassettes/ups/address_validation/valid_address.yml
- spec/friendly_shipping/services/ups/serialize_address_validation_request_spec.rb
- spec/friendly_shipping/services/ups_spec.rb
This adds the `<ConsigneeName />` element to the UPS address validation request serializer. The consignee name is critical to include to get accurate address classifications.
> Add consignee to address classification request

- .gitignore
- Gemfile
- spec/spec_helper.rb
Run the specs and open coverage/index.html to see the report. This will help us identify untested areas of the gem.
> Add simplecov for code coverage reports

- lib/friendly_shipping/services/ups/parse_xml_response.rb
- lib/friendly_shipping/services/usps/parse_xml_response.rb
- spec/friendly_shipping/services/ups/parse_xml_response_spec.rb
- spec/friendly_shipping/services/usps/parse_xml_response_spec.rb
Previously, invalid XML would still result in a valid Nokogiri document, but the root would be nil and no elements could be traversed. Instead, let's be noisy and raise an exception if the XML is invalid.
> Enable strict XML parsing

- CHANGELOG.md
- lib/friendly_shipping/services/ups_freight/generate_freight_rate_request_hash.rb
- lib/friendly_shipping/version.rb
- spec/cassettes/ups_freight/rates/success.yml
- spec/friendly_shipping/services/ups_freight_spec.rb
If we pass 'just' a Boolean, UPS will not return us information about the time in transit.
> Ups Freight: Pass TimeInTransitIndicator as a String

- CHANGELOG.md
- lib/friendly_shipping/services/ups_freight/generate_freight_rate_request_hash.rb
- lib/friendly_shipping/services/ups_freight/rates_options.rb
- lib/friendly_shipping/version.rb
- spec/cassettes/ups_freight/rates/success.yml
- spec/friendly_shipping/services/ups_freight/generate_freight_rate_request_hash_spec.rb
- spec/friendly_shipping/services/ups_freight/rates_options_spec.rb
- spec/friendly_shipping/services/ups_freight_spec.rb
This adds the UPS Freight PickupDate element to the rates API call. It doesn't seem to do much to the response, I've even tried with pickup on Christmas eve; nothing in the response seems to make a difference. But: we can now pass the element and see what it does.
> Add UPS Freight Pickup Date Element

- lib/friendly_shipping/services/ups/label_package_options.rb
- lib/friendly_shipping/services/ups/serialize_shipment_confirm_request.rb
- spec/friendly_shipping/services/ups/label_package_options_spec.rb
- spec/friendly_shipping/services/ups/serialize_shipment_confirm_request_spec.rb
I missed adding this option to the package options previously.
> Make ShipperReleaseIndicator accessible

- CHANGELOG.md
- lib/friendly_shipping/services/ups/serialize_shipment_confirm_request.rb
- lib/friendly_shipping/version.rb
In these two private methods, we compared instances of `Carmen::Country`
objects to strings, which would always yield false. This meant that no
shipment would ever allow package level reference numbers or delivery
confirmations.
> Use Country CODE instead of Country to compare with Country isos

- CHANGELOG.md
- lib/friendly_shipping/services/ups/serialize_shipment_address_snippet.rb
- lib/friendly_shipping/version.rb
- spec/friendly_shipping/services/ups/serialize_shipment_address_snippet_spec.rb
The label creation API from UPS needs a different XML tag to account for residential addresses than the rating API. This had been thought of previously in the source, but the indicator was not, actually changed.
> Fix shipment address indicator

- lib/friendly_shipping.rb
- lib/friendly_shipping/services/ship_engine/parse_rate_estimate_response.rb
This eliminates dozens of deprecation warnings about the rounding mode for `Money` being changed in the next major release. This also relocates the require statement to a central location since the `Money` class is being used in a lot of different places now.
> Explicitly set the Money rounding mode

- lib/friendly_shipping/services/ups.rb
- lib/friendly_shipping/services/ups/parse_time_in_transit_response.rb
- lib/friendly_shipping/services/ups/serialize_time_in_transit_request.rb
- lib/friendly_shipping/services/ups/timing_options.rb
- spec/cassettes/ups/timings/success.yml
- spec/fixtures/ups/ups_timing_api_response.xml
- spec/friendly_shipping/services/ups/parse_time_in_transit_response_spec.rb
- spec/friendly_shipping/services/ups/serialize_time_in_transit_request_spec.rb
- spec/friendly_shipping/services/ups/timing_options_spec.rb
- spec/friendly_shipping/services/ups_spec.rb
This adds UPS time-in-transit API calls to FriendlyShipping. Currently depends on #37 .
> Add UPS transit timings

- lib/friendly_shipping/services/ups/serialize_time_in_transit_request.rb
- spec/friendly_shipping/services/ups/serialize_time_in_transit_request_spec.rb
We should be including the destination city/state in our UPS timing requests.
> Add destination city/state to UPS timing serializer

- lib/friendly_shipping/services/ups/serialize_time_in_transit_request.rb
- spec/friendly_shipping/services/ups/serialize_time_in_transit_request_spec.rb
The time in transit API only allows shipments up to 150 pounds. However,
sometimes UPS will ship packages larger than this - to allow for that,
limit the weight we transmit to them to what their API thinks their maximum is.
> UPS: Transmit a maximum of 150 pounds to time in transit API

- CHANGELOG.md
- lib/friendly_shipping/version.rb
Tiny release with fixes for both UPS and USPS timing calls.
> Bump Version to 4.8.2, log changes

- .rubocop-relaxed.yml
This fixes:
`.rubocop-relaxed.yml: Layout/LineLength has the wrong namespace - should be Metrics`
> Move cop to the right namespace

- lib/friendly_shipping/services/ship_engine/label_options.rb
- lib/friendly_shipping/services/ship_engine/label_package_options.rb
- lib/friendly_shipping/services/ship_engine/rate_estimates_options.rb
- lib/friendly_shipping/services/ups/label_item_options.rb
- lib/friendly_shipping/services/ups/label_options.rb
- lib/friendly_shipping/services/ups/label_package_options.rb
- lib/friendly_shipping/services/ups_freight/rates_item_options.rb
- lib/friendly_shipping/services/ups_freight/rates_options.rb
- lib/friendly_shipping/services/ups_freight/rates_package_options.rb
☝️ 
Specs run without warnings under Ruby 2.7 (with the exception of incompatible 3rd party libraries).
https://blog.saeloun.com/2019/10/07/ruby-2-7-keyword-arguments-redesign.html
> Add double splats for Ruby 2.7 compatibility

- lib/friendly_shipping/services/usps/parse_time_in_transit_response.rb
- spec/fixtures/usps/time_in_transit_response.xml
Commitment sequences map information about when a USPS shipment arrives
to a short 5-digit code. We have a constant that lists all of them, but that was missing
one code. This missing code led to errors when parsing USPS time in transit responses
that contained it.
> Add missing commitment sequence

- lib/friendly_shipping/services/usps/parse_time_in_transit_response.rb
- spec/cassettes/usps/timings/success_without_timing_estimate.yml
- spec/friendly_shipping/services/usps_spec.rb
When estimating timing to non-contiguous US states, we get one estimate for
USPS First Class Package Service that does not, in fact, contain a timing
estimate, but rather a friendly message that it's difficult to ship things
there. This commit stops our parser from breaking with a NoMethodError in these cases.
> Fix timing estimation for users from Alaska and Hawaii

- lib/friendly_shipping/services/usps/choose_package_rate.rb
- lib/friendly_shipping/services/usps/parse_rate_response.rb
- lib/friendly_shipping/services/usps/serialize_rate_request.rb
- spec/friendly_shipping/services/usps/choose_package_rate_spec.rb
When requesting First Class rates, I ran into some errors. These two commits fix them: 
- In some cases, the API will return differing rates for "Metered" and "Stamped" mail, and I don't think anyone will really use the rating API for that kind of Mail. We just return the first, more standard type of mail and do not raise an error if we're not down to exactly one shipping quote in the ChoosePackageRate class.
- Identify packages by index rather than by randomly generated ID to facilitate using tools like VCR for recording.
> Fix USPS rate response parsing 

- lib/friendly_shipping/services/usps/serialize_rate_request.rb
- spec/friendly_shipping/services/usps/serialize_rate_request_spec.rb
When we specify a particular USPS-branded box type, they know the
dimensions.
> USPS: Only specify package dimensions for variable and regular packages

- lib/friendly_shipping/services/usps/parse_time_in_transit_response.rb
- spec/cassettes/usps/timings/success_with_invalid_commitment_seq.yml
- spec/fixtures/usps/time_in_transit_response_with_invalid_commitment_seq.xml
- spec/friendly_shipping/services/usps/parse_time_in_transit_response_spec.rb
- spec/friendly_shipping/services/usps_spec.rb
Sometimes USPS returns `CommitmentSeq` elements with invalid codes. This change ensures that we just skip those commitments instead of raising an exception.
> Skip timing commitments with invalid sequences

- lib/friendly_shipping/services/usps/parse_time_in_transit_response.rb
- spec/friendly_shipping/services/usps/parse_time_in_transit_response_spec.rb
Sometimes, USPS returns an EAD of "0001-01-01". This is obviously bogus,
so let's use the "Acceptance Date" date USPS returns instead of the
bogus date.
> USPS: Use "Acceptance Date" if "Effective Acceptance Date" invalid

- Gemfile
- friendly_shipping.gemspec
This seems like a more appropriate place for development dependencies in a gem vs an app. However, I don't feel particularly strongly about this. Any thoughts? See: https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/
> Move development dependencies to gemspec

- .circleci/config.yml
- .rubocop.yml
- friendly_shipping.gemspec
Recent versions of ActiveSupport will not run with Ruby 2.4, thus making
our test suite fail.
See https://circleci.com/gh/friendlycart/friendly_shipping/306
> Bump Ruby version

- lib/friendly_shipping/services/ups.rb
- lib/friendly_shipping/services/ups/rate_estimate_options.rb
- lib/friendly_shipping/services/ups/rate_estimate_package_options.rb
- lib/friendly_shipping/services/ups/serialize_package_node.rb
- lib/friendly_shipping/services/ups/serialize_rating_service_selection_request.rb
- lib/friendly_shipping/services/usps.rb
- lib/friendly_shipping/services/usps/choose_package_rate.rb
- lib/friendly_shipping/services/usps/parse_package_rate.rb
- lib/friendly_shipping/services/usps/parse_rate_response.rb
- lib/friendly_shipping/services/usps/rate_estimate_options.rb
- lib/friendly_shipping/services/usps/rate_estimate_package_options.rb
- lib/friendly_shipping/services/usps/serialize_rate_request.rb
- spec/friendly_shipping/services/ups/rate_estimate_package_options_spec.rb
- spec/friendly_shipping/services/ups/rate_estimates_options_spec.rb
- spec/friendly_shipping/services/ups/serialize_package_node_spec.rb
- spec/friendly_shipping/services/ups/serialize_rating_service_selection_request_spec.rb
- spec/friendly_shipping/services/ups_spec.rb
- spec/friendly_shipping/services/usps/choose_package_rate_spec.rb
- spec/friendly_shipping/services/usps/parse_package_rate_spec.rb
- spec/friendly_shipping/services/usps/parse_rate_response_spec.rb
- spec/friendly_shipping/services/usps/rate_estimate_package_options_spec.rb
- spec/friendly_shipping/services/usps/rate_estimates_options_spec.rb
- spec/friendly_shipping/services/usps/serialize_rate_request_spec.rb
This changes the method signatures of the `rate_estimates` methods on the UPS and USPS services to allow more complex option objects. Now, we can use the same `Physical::Shipment` object for calls to both services, and only have to generate an objects object for them. This is a pattern already implement for ShipEngine and UPS Freight, as well as on e.g. the `timing` methods on all services. 
Adding to this refactoring, we can now specify on a package level whether we want to transmit dimensions or not.
> Use options objects for UPS and USPS rate estimation

- lib/friendly_shipping/services/usps/parse_time_in_transit_response.rb
- lib/friendly_shipping/services/usps/shipping_methods.rb
- spec/friendly_shipping/services/usps/parse_rate_response_spec.rb
- spec/friendly_shipping/services/usps/parse_time_in_transit_response_spec.rb
The correct name for this mail class is simply "Package Services." After doing some research on the USPS web site, I realized that the "Package Services" mail class actually encapsulates USPS Retail Ground, Media Mail, and a few other oddball shipping methods. It doesn't appear to have anything to do with First Class shipping, therefore the words "First-Class" shouldn't be in the name.
This rename also fixes a bug where USPS rate responses that included both FC and Package Services quotes would assign the FC quote to the Package Services shipping method since that shipping method had the words "First-Class" in it but had a longer name than just "First-Class."
> Rename "First-Class Package Service" to "Package Services"

- lib/friendly_shipping/request.rb
- lib/friendly_shipping/services/ups.rb
- lib/friendly_shipping/services/usps.rb
- spec/friendly_shipping/request_spec.rb
Since we're saving the original request bodies in our app for later troubleshooting/debugging, it's helpful to have human-readable forms of each payload. For USPS this means the unencoded XML outside of the query string. For UPS this means just the core XML without the access request.
I'm open to suggestions for a better name than "readable body."
> Add readable request bodies

- lib/friendly_shipping/services/ups/parse_xml_response.rb
- spec/friendly_shipping/services/ups/parse_xml_response_spec.rb
In the event that an unexpected root tag was received in an XML response, the UPS parser is supposed to return a failure. Due to a typo the parser was bypassing this branch entirely.
> Fix handling invalid XML docs in UPS parser

- lib/friendly_shipping/services/ups/parse_address_classification_response.rb
- lib/friendly_shipping/services/ups/parse_address_validation_response.rb
- lib/friendly_shipping/services/ups/parse_city_state_lookup_response.rb
- lib/friendly_shipping/services/ups/parse_rate_response.rb
- lib/friendly_shipping/services/ups/parse_shipment_accept_response.rb
- lib/friendly_shipping/services/ups/parse_shipment_confirm_response.rb
- lib/friendly_shipping/services/ups/parse_time_in_transit_response.rb
- lib/friendly_shipping/services/ups/parse_void_shipment_response.rb
- lib/friendly_shipping/services/ups/parse_xml_response.rb
- lib/friendly_shipping/services/usps/parse_address_validation_response.rb
- lib/friendly_shipping/services/usps/parse_city_state_lookup_response.rb
- lib/friendly_shipping/services/usps/parse_rate_response.rb
- lib/friendly_shipping/services/usps/parse_time_in_transit_response.rb
- lib/friendly_shipping/services/usps/parse_xml_response.rb
- spec/friendly_shipping/services/ups/parse_xml_response_spec.rb
- spec/friendly_shipping/services/ups_spec.rb
- spec/friendly_shipping/services/usps/parse_xml_response_spec.rb
Previously we were returning simple strings on failure. It's nice to have the original request/response available in debug mode. The `ApiFailure` class seems appropriate.
> Wrap UPS/USPS failure responses in ApiFailure class

- .rubocop-relaxed.yml
- .rubocop.yml
- friendly_shipping.gemspec
When running the latest version of Rubocop in CI:
```bash
.rubocop-relaxed.yml: Metrics/LineLength has the wrong namespace - should be Layout
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Style/HashEachMethods (0.80)
- Style/HashTransformKeys (0.80)
- Style/HashTransformValues (0.80)
For more information: https://docs.rubocop.org/en/latest/versioning/
```
This PR adds the missing cops and fixes the namespace problem, along with updating our gemspec to the latest version of Rubocop.
> Add missing cops to fix warnings

- lib/friendly_shipping/api_failure.rb
- spec/friendly_shipping/api_failure_spec.rb
- spec/friendly_shipping/services/ups/parse_xml_response_spec.rb
- spec/friendly_shipping/services/ups_spec.rb
- spec/friendly_shipping/services/usps/parse_xml_response_spec.rb
These are similar enough that they should probably be related this way.
> Refactor ApiFailure to subclass ApiResult

- lib/friendly_shipping/http_client.rb
- lib/friendly_shipping/services/ship_engine/bad_request_handler.rb
- lib/friendly_shipping/services/ups_freight/restful_api_error_handler.rb
- spec/friendly_shipping/http_client_spec.rb
- spec/friendly_shipping/services/ship_engine_spec.rb
- spec/friendly_shipping/services/ups_freight/restful_api_error_handler_spec.rb
- spec/friendly_shipping/services/ups_freight_spec.rb
We wrap all of our errors in ApiFailure objects since version 0.5.3, but
we missed the HTTP errors, where we also want to use our ApiFailure
class.
> Wrap HTTP errors in ApiFailure objects

- lib/friendly_shipping/services/ups/parse_time_in_transit_response.rb
- spec/fixtures/ups/ups_timing_without_pickup_time.xml
- spec/friendly_shipping/services/ups/parse_time_in_transit_response_spec.rb
Sometimes, UPS will give us a pickup date but no pickup time. This
commit accounts for these instances.
> Fix NoMethodError when UPS pickup time is not given

- CHANGELOG.md
- lib/friendly_shipping/version.rb
Release 0.6.2 with a fix for non-existing PickupTime elements
> Bump version and update changelog

- lib/friendly_shipping/services/usps/parse_time_in_transit_response.rb
- lib/friendly_shipping/services/usps/shipping_methods.rb
- spec/friendly_shipping/services/usps/choose_package_rate_spec.rb
- spec/friendly_shipping/services/usps/parse_package_rate_spec.rb
- spec/friendly_shipping/services/usps/parse_rate_response_spec.rb
- spec/friendly_shipping/services/usps/parse_time_in_transit_response_spec.rb
- spec/friendly_shipping/services/usps/serialize_rate_request_spec.rb
Instead of programmatically generating USPS service codes to match against rates returned by the API, let's specify the codes inline the way we already do for UPS and Freight shipping methods.
> Use explicit USPS service codes

- lib/friendly_shipping/services/usps/rate_estimate_package_options.rb
- spec/friendly_shipping/services/usps/rate_estimate_package_options_spec.rb
When hold for pickup is enabled, we need to append HFP to the service code that gets included in the USPS rate request. Otherwise, the rate we get back won't be the hold for pickup rate.
> Append HFP to service code in rate options

- lib/friendly_shipping/services/usps/parse_package_rate.rb
- lib/friendly_shipping/services/usps/shipping_methods.rb
- lib/friendly_shipping/shipping_method.rb
- spec/friendly_shipping/services/usps/parse_package_rate_spec.rb
- spec/friendly_shipping/shipping_method_spec.rb
This updates the code that matches USPS API rates with Friendly shipping methods to first attempt to match by the `CLASSID` attribute, then fall back to name (`MailService` element) if that fails. This should be a more reliable way to match shipping methods with potentially ambiguous names like Priority Mail vs. Priority Mail Express.
This also eliminates the need for special handling of Priority Mail vs. Priority Mail Express matching since we can simply provide class IDs for Express which will be matched against. This is better than matching names starting with "Priority" and sorting by length which is what was being done prior.
> Match USPS API rates by class ID before falling back to name

- lib/friendly_shipping/services/usps/parse_package_rate.rb
- lib/friendly_shipping/services/usps/rate_estimate_package_options.rb
- lib/friendly_shipping/services/usps/shipping_methods.rb
- spec/friendly_shipping/services/usps/parse_package_rate_spec.rb
- spec/friendly_shipping/services/usps/rate_estimate_package_options_spec.rb
This adds a shipping method and supporting code for the USPS Priority Mail Cubic shipping method.
This shipping method is an outlier in that it always returns a Commercial Plus rate in the API response, even though the service name passed to the API is simply `PRIORITY MAIL CUBIC` without a `COMMERCIAL` modifier.
Something else to note is that, while the API accepts container names of `CUBIC PARCELS` or `CUBIC SOFT PACK`, there is no difference in rates versus using the `VARIABLE` container name.
> Add USPS Priority Mail Cubic shipping method

- lib/friendly_shipping/services/ups/parse_rate_response.rb
- spec/fixtures/ups/ups_rates_api_response.xml
- spec/friendly_shipping/services/ups/parse_rate_response_spec.rb
**Depends on #117**
This adds package and shipment-level negotiated charges to the returned UPS rates. These will only be present when negotiated rates have been requested from the API.
> Include negotiated charges for UPS

- lib/friendly_shipping/services/ups/parse_rate_response.rb
- spec/friendly_shipping/services/ups/parse_rate_response_spec.rb
We were already returning package-level itemized charges in UPS rates. This adds shipment-level itemized charges to the same rates. Shipment-level itemized charges typically consist of the residential surcharge (if any).
> Include shipment-level itemized charges for UPS

- .github/dependabot.yml
This activates dependency updates for this repo by adding a Dependabot config file.
Documentation for Dependabot can be found here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically
Closes #108.
> Configure dependency updates for this repo

- friendly_shipping.gemspec
This updates our gemspec to use a more recent version of bundler (bundler 2.1.4 is included with Ruby 2.7.2).
> Update bundler to 2.1.4

- lib/friendly_shipping/services/usps/parse_package_rate.rb
- lib/friendly_shipping/services/usps/rate_estimate_package_options.rb
- lib/friendly_shipping/services/usps/serialize_rate_request.rb
- spec/fixtures/usps/usps_rates_api_response_with_fees.xml
- spec/friendly_shipping/services/usps/parse_package_rate_spec.rb
- spec/friendly_shipping/services/usps/parse_rate_response_spec.rb
- spec/friendly_shipping/services/usps/rate_estimate_package_options_spec.rb
- spec/friendly_shipping/services/usps/serialize_rate_request_spec.rb
This adds support for new USPS fees. The USPS rate request serializer includes an optional `ReturnFees` tag in the request when the package options `return_fees` boolean is set to true. If the `Fees` tag is present in the API response, each fee will be parsed and added to the `Rate` in the data hash.
> Add support for USPS fees

- lib/friendly_shipping/services/usps/parse_package_rate.rb
- lib/friendly_shipping/services/usps/rate_estimate_package_options.rb
- lib/friendly_shipping/services/usps/serialize_rate_request.rb
- spec/fixtures/usps/usps_rates_api_response_with_dimensional_weight_rate.xml
- spec/friendly_shipping/services/usps/parse_package_rate_spec.rb
- spec/friendly_shipping/services/usps/parse_rate_response_spec.rb
- spec/friendly_shipping/services/usps/rate_estimate_package_options_spec.rb
- spec/friendly_shipping/services/usps/serialize_rate_request_spec.rb
This adds support for optionally including USPS calculated dimensional weight in the response. The USPS rate request serializer includes an optional `ReturnDimensionalWeight` tag in the request when the package options `return_dimensional_weight` boolean is set to true. If the `DimensionalWeightRate` tag is present in the API response, the value will be parsed and added to the `Rate` in the data hash.
I'm setting this to `true` by default which seems reasonable since the value is only included in the response if the package dimensions actually qualify for dimensional rates.
> Optionally include USPS dimensional weight in response

- lib/friendly_shipping.rb
- lib/friendly_shipping/services/ups_freight/parse_freight_label_response.rb
- lib/friendly_shipping/services/ups_freight/shipment_information.rb
- spec/fixtures/ups_freight/labels/success.json
- spec/friendly_shipping/services/ups_freight/parse_freight_label_response_spec.rb
- spec/friendly_shipping/services/ups_freight/shipment_information_spec.rb
This updates how we parse the UPS Freight shipping label response to include a cost breakdown on the `ShippingInformation` instance that's returned.
> Parse UPS Freight cost breakdown from shipping label API response

- lib/friendly_shipping/api_error.rb
- spec/friendly_shipping/api_error_spec.rb
This updates the `ApiError` class to set the message from the cause when a message isn't passed to the initializer.
> Use message from `cause` when API error message not set

- lib/friendly_shipping/services/ups_freight/generate_location_hash.rb
- spec/friendly_shipping/services/ups_freight/generate_location_hash_spec.rb
When generating location hashes for TForce Freight, fall back on the person's name if the company name is blank. This avoids errors from the API about a missing name in `ShipTo` when company is not provided.
> Use person name when company name is blank

- lib/friendly_shipping/services/ups_freight/generate_freight_ship_request_hash.rb
- lib/friendly_shipping/services/ups_freight/generate_reference_hash.rb
- lib/friendly_shipping/services/ups_freight/label_options.rb
- spec/friendly_shipping/services/ups_freight/generate_freight_ship_request_hash_spec.rb
- spec/friendly_shipping/services/ups_freight/generate_reference_hash_spec.rb
- spec/friendly_shipping/services/ups_freight/label_options_spec.rb
This adds support for passing reference numbers in Freight label options. These reference numbers appear on the Bill of Lading. Each reference number has a code and a value. Reference numbers are passed into the label options as an array of hashes, each hash containing code and value keys. For example:
```ruby
FriendlyShipping::Services::UpsFreight::LabelOptions.new(
reference_numbers: [
{
code: :bill_of_lading_number,
value: "43195814"
},{
code: :consignee_reference,
value: "A983194"
}
]
)
```
A table of reference number codes can be found in the TForce API documentation, as well as at `FriendlyShipping::Services::UpsFreight::GenerateReferenceHash::REFERENCE_NUMBER_CODES`
> Support Freight reference numbers

- lib/friendly_shipping/api_error_handler.rb
- lib/friendly_shipping/http_client.rb
- lib/friendly_shipping/response.rb
- spec/friendly_shipping/api_error_handler_spec.rb
- spec/friendly_shipping/response_spec.rb
This updates our default API error handler to return a `FriendlyShipping::Response` as the original response instead of the underlying `RestClient::Response` when an HTTP error occurs (i.e. 503 gateway error).
This ensures anyone using our HTTP client will receive a consistent response class whether they get a successful response from the API, an error response from the API, or an HTTP error response.
For a successful response or an API error, the value returned by the client will be a `FriendlyShipping::Response`.  For an HTTP error which triggers the error handler, the original response retrieved from the `ApiFailure` will also be a `FriendlyShipping::Response` instead of a `RestClient::Response`.
> Use `FriendlyShipping::Response` in default error handler

- friendly_shipping.gemspec
The URI gem has changed its public API with this version, breaking compatibility with the largely unmaintained `data_uri` gem. This fixes the co-dependency issue for now; once this PR in `data_uri` is merged we can update to the newest `uri` gem:
https://github.com/dball/data_uri/pull/10
> Restrict URI gem to < 0.11.0

- lib/friendly_shipping/request.rb
- lib/friendly_shipping/services/ship_engine.rb
- lib/friendly_shipping/services/ups.rb
- lib/friendly_shipping/services/ups_freight.rb
- lib/friendly_shipping/services/usps.rb
This optional attr indicates which HTTP method was used for a given request. It can be returned in a `Request` object.
This is useful for logging or displaying details about API requests/responses without having to assume which HTTP method Friendly Shipping is using for a given carrier API request.
> Add optional `http_method` attr to `Request` class

- lib/friendly_shipping/services/ups_freight/generate_location_hash.rb
- spec/friendly_shipping/services/ups_freight/generate_freight_rate_request_hash_spec.rb
- spec/friendly_shipping/services/ups_freight/generate_location_hash_spec.rb
TForce (formerly UPS Freight) accepts multiple address lines as an array. The first and second address lines, when provided, will appear on the shipping label and BOL shipping documents.
> Pass multiple address lines to TForce correctly

- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
[ShipEngine Documentation](https://shipengine.github.io/shipengine-openapi/#operation/create_label) PackageCode `package` is considered a custom or unknown package type. As such the dimensions should be included to ensure best rate for creating a label
> Include Dimensions regardless of package_code

- lib/friendly_shipping/services/ship_engine/label_options.rb
- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
- spec/friendly_shipping/services/ship_engine/label_options_spec.rb
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
To print an image on labels with ShipEngine you need to include label_image_id with Label options 
[ShipEngine Documentation](https://www.shipengine.com/docs/labels/branding/#example)
> ShipEngine Label Image

- lib/friendly_shipping/services/ups/parse_shipment_accept_response.rb
- lib/friendly_shipping/services/ups/serialize_shipment_confirm_request.rb
- spec/friendly_shipping/services/ups/serialize_shipment_confirm_request_spec.rb
This change allows billing for international shipments to have first party billing for the shipping and third party for the duties and fees.
There are a couple of small changes for conditions that UPS enforces: truncate contents description to UPS max, protect against nil shipment cost
> Allow ups international billing for duties and fees only 

- lib/friendly_shipping/services/ship_engine/label_customs_options.rb
- lib/friendly_shipping/services/ship_engine/label_item_options.rb
- lib/friendly_shipping/services/ship_engine/label_options.rb
- lib/friendly_shipping/services/ship_engine/label_package_options.rb
- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
- lib/friendly_shipping/services/usps_international.rb
- lib/friendly_shipping/services/usps_international/parse_rate_response.rb
- spec/friendly_shipping/services/ship_engine/label_customs_options_spec.rb
- spec/friendly_shipping/services/ship_engine/label_item_options_spec.rb
- spec/friendly_shipping/services/ship_engine/label_options_spec.rb
- spec/friendly_shipping/services/ship_engine/label_package_options_spec.rb
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
- spec/friendly_shipping/services/usps_international/rate_estimate_package_options_spec.rb
This serializes customs information as part of the ShipEngine label request, thus enabling us to generate international shipping labels. Without the customs information, ShipEngine rejects the request if an international shipping method is being used (i.e. USPS First-Class Package International, USPS Priority Mail International, etc).
> Add ShipEngine support for international labels

- lib/friendly_shipping/services/ups/serialize_address_snippet.rb
- lib/friendly_shipping/services/ups/serialize_shipment_confirm_request.rb
- spec/friendly_shipping/services/ups/serialize_shipment_confirm_request_spec.rb
UPS International Shipping requires both CompanyName and AttentionName for ShipTo address
> UPS ShipTo International Constraint

- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
We were sending a test shipment to Canada using USPS First Class as the shipping method and the warehouse ran into this error when they tried to print the shipping label:
```
request.shipment.customs.customs_items[0].value.currency: Unexpected token StartObject when parsing enum.
```
We determined that this was because the currency being passed in was not setting to 'USD'. In updating the method `serialize_customs_items` so that the currency is always set to a string, we get rid of the `Money::Currency` object that was causing the printing error.
> Update SerializeLabelShipment to avoid label printing error

- lib/friendly_shipping/services/ups/label_item_options.rb
- lib/friendly_shipping/services/ups/serialize_shipment_confirm_request.rb
- spec/friendly_shipping/services/ship_engine/label_item_options_spec.rb
- spec/friendly_shipping/services/ups/label_item_options_spec.rb
- spec/friendly_shipping/services/ups/serialize_shipment_confirm_request_spec.rb
This adds country of origin to the item options used when serializing UPS label requests, enabling different origin countries to be used for different products in the package when requesting paperless invoicing.
> Use item options country of origin in UPS label requests

- lib/friendly_shipping/services/ups_freight/api_error.rb
- spec/friendly_shipping/services/ups_freight/api_error_spec.rb
If a timeout error occurs, we won't have a response body to parse. We can use the timeout exception's message instead.
> Handle TForce API timeout responses

- lib/friendly_shipping/services/ups/serialize_shipment_confirm_request.rb
- spec/friendly_shipping/services/ups/serialize_shipment_confirm_request_spec.rb
For the ups shipment confirm request, truncate the product description for international products to 35 characters (the UPS limit). UPS will reject the request if the product description is too long.
> Truncate UPS international product description

- lib/friendly_shipping/rate.rb
Fixes a deprecation warning that appears when using Rails 7 with this gem.
```
DEPRECATION WARNING: Rails 7.0 has deprecated Enumerable.sum in favor of Ruby's native implementation available since 2.4. Sum of non-numeric elements requires an initial argument.
```
> Fix Rails 7 deprecation warning

- lib/friendly_shipping/services/usps_international/serialize_rate_request.rb
- spec/friendly_shipping/services/usps_international/serialize_rate_request_spec.rb
Before this change, a package that weighs 3 pounds would get quoted as a package that weighs 3 pounds and 48 ounces (6 pounds).
> USPS international package weight ounces is remainder after pounds conversion

- lib/friendly_shipping/services/ups/serialize_package_node.rb
- spec/friendly_shipping/services/ups/serialize_package_node_spec.rb
UPS international shipments over a certain threshold require a package-level declared value to be present in the request. We naively calculate the delcared value by summing item cost. A future enhancement could allow a separate value to be passed if we want to enable the actual cost of each item to be used instead of the amount charged to the customer.
> Add declared value to UPS package serializer

- lib/friendly_shipping/services/ups/label_package_options.rb
- lib/friendly_shipping/services/ups/serialize_shipment_confirm_request.rb
- spec/friendly_shipping/services/ups/label_package_options_spec.rb
As a follow on to https://github.com/friendlycart/friendly_shipping/pull/168, this boolean causes the declared value (calculated as the sum of all items in the shipment) to be included in the label API request.
This change enables end users to specify whether they want declared value included when instantiating the `LabelPackageOptions` class for the API call.
> Add declared to UPS label package options

- lib/friendly_shipping/services/ups_freight/generate_location_hash.rb
- lib/friendly_shipping/services/usps/parse_package_rate.rb
- lib/friendly_shipping/services/usps_international/parse_package_rate.rb
- spec/friendly_shipping/services/ups_freight/generate_location_hash_spec.rb
The UPS Freight (TForce) API returns an error response if certain values in the request exceed a certain length.
> Truncate long values in UPS Freight label request

- lib/friendly_shipping/services/usps/parse_time_in_transit_response.rb
- lib/friendly_shipping/services/usps/shipping_methods.rb
This adds support for the new USPS Ground Advantage shipping method scheduled to become active on July 9, 2023. This new shipping method replaces the existing First Class Package Service shipping method, although the API will continue responding to FCPS requests but with rates and timings for Ground Advantage.
> Add new USPS Ground Advantage shipping method

- lib/friendly_shipping/services/ups/serialize_shipment_confirm_request.rb
- spec/friendly_shipping/services/ups/serialize_shipment_confirm_request_spec.rb
This adds AccountNumber and TaxIdentificationNumber to the Shipment/SoldTo node for international shipments to support NRI options.
The AccountNumber is new and was just added to the api by UPS a couple months ago.
> Add new billing options for NRI

- lib/friendly_shipping/services/rl/bol_options.rb
- lib/friendly_shipping/services/rl/bol_packages_serializer.rb
- lib/friendly_shipping/services/rl/rate_quote_options.rb
- lib/friendly_shipping/services/rl/rate_quote_packages_serializer.rb
- lib/friendly_shipping/services/rl/serialize_create_bol_request.rb
- lib/friendly_shipping/services/rl/serialize_rate_quote_request.rb
- spec/friendly_shipping/services/rl/bol_options_spec.rb
- spec/friendly_shipping/services/rl/bol_packages_serializer_spec.rb
- spec/friendly_shipping/services/rl/rate_quote_options_spec.rb
- spec/friendly_shipping/services/rl/rate_quote_packages_serializer_spec.rb
- spec/friendly_shipping/services/rl/serialize_create_bol_request_spec.rb
This enables alternate package serializer behavior to be provided by configuring the options with a callable class.
> Extract R&L Freight package serializer classes

- lib/friendly_shipping/services/rl/bol_options.rb
- lib/friendly_shipping/services/rl/serialize_create_bol_request.rb
- spec/friendly_shipping/services/rl/bol_options_spec.rb
- spec/friendly_shipping/services/rl/serialize_create_bol_request_spec.rb
Reference numbers appear on the Bill of Lading itself and can be anything the user wants them to be.
> Add reference numbers to R+L BOL options class

- lib/friendly_shipping/services/ups/label_options.rb
- lib/friendly_shipping/services/ups/rate_estimate_options.rb
- lib/friendly_shipping/services/ups/serialize_rating_service_selection_request.rb
- lib/friendly_shipping/services/ups/serialize_shipment_accept_request.rb
- lib/friendly_shipping/services/ups/serialize_shipment_confirm_request.rb
- spec/friendly_shipping/services/ups/label_options_spec.rb
- spec/friendly_shipping/services/ups/rate_estimates_options_spec.rb
- spec/friendly_shipping/services/ups/serialize_rating_service_selection_request_spec.rb
- spec/friendly_shipping/services/ups/serialize_shipment_accept_request_spec.rb
- spec/friendly_shipping/services/ups/serialize_shipment_confirm_request_spec.rb
The sub-version (default 1707) specifies which version of the UPS API to use. This controls which features are available/visible in requests and responses. Being able to pass a non-default sub-version is desirable.
> Add sub-version option to UPS rate/shipping requests

- lib/friendly_shipping/services/rl/rate_quote_packages_serializer.rb
- spec/friendly_shipping/services/rl/rate_quote_packages_serializer_spec.rb
Include dimensions when serializing packages to ensure we are able to generate quotes from R+L for destinations outside of domestic USA and Canada
> R+L Shipping outside of Domestic USA & Canada requires dimensions

- lib/friendly_shipping/services/rl.rb
- spec/cassettes/rl/create_bill_of_lading/failure.yml
- spec/cassettes/rl/create_bill_of_lading/success.yml
- spec/cassettes/rl/print_bill_of_lading/success.yml
- spec/cassettes/rl/print_shipping_labels/success.yml
The rates/timings still use the live API URL, but for BOLs and labels we can use the new sandbox API URL to avoid creating actual pickup requests and being charged for them.
> Use R+L Carriers sandbox API for test mode

- lib/friendly_shipping/services/ups/rate_estimate_options.rb
- lib/friendly_shipping/services/ups/serialize_rating_service_selection_request.rb
- spec/friendly_shipping/services/ups/rate_estimate_options_spec.rb
- spec/friendly_shipping/services/ups/serialize_rating_service_selection_request_spec.rb
The pickup date can be used to get a rate quote for a date up to 35 days into the past or 60 days into the future.
If a date is not provided or is invalid, it will be defaulted to the current system date.
> Add optional pickup date to UPS rate requests

- .circleci/config.yml
- lib/friendly_shipping/api_error.rb
- lib/friendly_shipping/services/rl/api_error.rb
- lib/friendly_shipping/services/ship_engine/api_error.rb
- lib/friendly_shipping/services/ship_engine/parse_rates_response.rb
- lib/friendly_shipping/services/ship_engine/rates_package_options.rb
- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
- lib/friendly_shipping/services/ups_freight/api_error.rb
- spec/friendly_shipping/services/ship_engine/parse_label_response_spec.rb
- spec/friendly_shipping/services/ship_engine/parse_rate_estimates_response_spec.rb
- spec/friendly_shipping/services/ship_engine/parse_rates_response_spec.rb
Updates the CI to run Ruby 3.2 instead of 2.7, and fixes a few rubocop offenses.
> Rubocop fixes

- lib/friendly_shipping/services/ups_freight/parse_freight_label_response.rb
- lib/friendly_shipping/services/ups_freight/shipment_information.rb
- spec/friendly_shipping/services/ups_freight/parse_freight_label_response_spec.rb
- spec/friendly_shipping/services/ups_freight/shipment_information_spec.rb
This renames the TForce (UPS Freight) attr from `number` to `pro_number` to better represent what it actually is.
An alias is added to ensure backwards compatibility.
> Rename `ShipmentInformation#number` attribute

- lib/friendly_shipping/services/ups_freight/shipment_information.rb
- spec/friendly_shipping/services/ups_freight/shipment_information_spec.rb
This makes _setting_ the `number` attribute backwards compatible after the attribute was renamed to `pro_number` in [this PR](https://github.com/friendlycart/friendly_shipping/pull/196).
> Allow setting `ShipmentInformation#number` value

- lib/friendly_shipping/services/ups/label_options.rb
- lib/friendly_shipping/services/ups/serialize_shipment_confirm_request.rb
- spec/friendly_shipping/services/ups/serialize_shipment_confirm_request_spec.rb
UPS may decide to hold a shipment for processing through customs for various reasons. Adding this statement will (hopefully) allow the shipment to go through without requiring a phone call or email.
> Add declaration statement to UPS intl labels

- lib/friendly_shipping.rb
- lib/friendly_shipping/inflections.rb
- lib/friendly_shipping/services/tforce_freight.rb
- lib/friendly_shipping/services/tforce_freight/api_error.rb
- lib/friendly_shipping/services/tforce_freight/generate_commodity_information.rb
- lib/friendly_shipping/services/tforce_freight/generate_location_hash.rb
- lib/friendly_shipping/services/tforce_freight/generate_rates_request_hash.rb
- lib/friendly_shipping/services/tforce_freight/parse_rates_response.rb
- lib/friendly_shipping/services/tforce_freight/rates_item_options.rb
- lib/friendly_shipping/services/tforce_freight/rates_options.rb
- lib/friendly_shipping/services/tforce_freight/rates_package_options.rb
- lib/friendly_shipping/services/tforce_freight/shipping_methods.rb
- spec/cassettes/tforce_freight/rates/failure.yml
- spec/cassettes/tforce_freight/rates/success.yml
- spec/fixtures/tforce_freight/failure_with_http_error.json
- spec/fixtures/tforce_freight/rates/success.json
- spec/friendly_shipping/services/tforce_freight/api_error_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_commodity_information_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_location_hash_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_rates_request_hash_spec.rb
- spec/friendly_shipping/services/tforce_freight/parse_rates_response_spec.rb
- spec/friendly_shipping/services/tforce_freight/rates_item_options_spec.rb
- spec/friendly_shipping/services/tforce_freight/rates_options_spec.rb
- spec/friendly_shipping/services/tforce_freight/rates_package_options_spec.rb
- spec/friendly_shipping/services/tforce_freight/shipping_methods_spec.rb
- spec/friendly_shipping/services/tforce_freight_spec.rb
TForce (formerly UPS Freight) is building [a new API](https://developer.tforcefreight.com/) distinct from UPS. This commit introduces a new service class for this API and implements the [Get Rate](https://developer.tforcefreight.com/api-details#api=rating&operation=get-rate) call.
> Implement new TForce API rates call

- friendly_shipping.gemspec
- lib/friendly_shipping/services/tforce_freight.rb
- lib/friendly_shipping/services/tforce_freight/access_token.rb
- lib/friendly_shipping/services/tforce_freight/generate_commodity_information.rb
- lib/friendly_shipping/services/tforce_freight/generate_location_hash.rb
- lib/friendly_shipping/services/tforce_freight/generate_rates_request_hash.rb
- spec/friendly_shipping/services/tforce_freight/access_token_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_commodity_information_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_location_hash_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_rates_request_hash_spec.rb
- spec/friendly_shipping/services/tforce_freight_spec.rb
This endpoint is used to create a new JWT access token. Once created, the token can be used to make additional API calls.
Tokens have a default life span of 60 mins. Once expired, a new token must be created to continue making API calls.
See https://developer.tforcefreight.com/resources/integration-end-user
> Add TForce endpoint to create access token

- lib/friendly_shipping/services/tforce_freight/api_error.rb
- spec/fixtures/tforce_freight/failure_with_api_error.json
- spec/friendly_shipping/services/tforce_freight/api_error_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_rates_request_hash_spec.rb
As it turns out, TForce returns errors in 2 different formats. We were already parsing HTTP error responses correctly, but errors coming from the API itself have a different format. This commit updates the `ApiError` class to parse these errors correctly.
> Adjust TForce error parser for API errors

- lib/friendly_shipping/services/tforce_freight/generate_location_hash.rb
- spec/friendly_shipping/services/tforce_freight/generate_location_hash_spec.rb
TForce requires zips to be truncated to 5 digits. An API error is returned otherwise.
> Truncate zips to 5 digits for TForce

- lib/friendly_shipping/services/ship_engine/customs_items_serializer.rb
- lib/friendly_shipping/services/ship_engine/label_options.rb
- lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
- spec/friendly_shipping/services/ship_engine/customs_items_serializer_spec.rb
- spec/friendly_shipping/services/ship_engine/label_options_spec.rb
- spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb
APC has a hard limit of 35 line items per shipment. Since the most commonly ordered items are fragrance oils and they all (or mostly all) are identical for customs purposes, they can be consolidated so that the overall number of line items for the label are reduced.
This is more of a stopgap than a fix since it doesn't consider the 35 limit at all. This should catch at least 90% of the cases. This and the weight limit on the shipment combined should minimize the number of too many items failures.
> Consolidate customs items for ShipEngine

- lib/friendly_shipping/services/tforce_freight.rb
- lib/friendly_shipping/services/tforce_freight/bol_options.rb
- lib/friendly_shipping/services/tforce_freight/document_options.rb
- lib/friendly_shipping/services/tforce_freight/generate_commodity_information.rb
- lib/friendly_shipping/services/tforce_freight/generate_create_bol_request_hash.rb
- lib/friendly_shipping/services/tforce_freight/generate_document_options_hash.rb
- lib/friendly_shipping/services/tforce_freight/generate_handling_units_hash.rb
- lib/friendly_shipping/services/tforce_freight/generate_reference_hash.rb
- lib/friendly_shipping/services/tforce_freight/parse_create_bol_response.rb
- lib/friendly_shipping/services/tforce_freight/rates_options.rb
- lib/friendly_shipping/services/tforce_freight/rates_package_options.rb
- spec/cassettes/tforce_freight/create_bol/failure.yml
- spec/cassettes/tforce_freight/create_bol/success.yml
- spec/fixtures/tforce_freight/create_bol/success.json
- spec/friendly_shipping/services/tforce_freight/bol_options_spec.rb
- spec/friendly_shipping/services/tforce_freight/document_options_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_commodity_information_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_create_bol_request_hash_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_document_options_hash_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_handling_units_hash_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_reference_hash_spec.rb
- spec/friendly_shipping/services/tforce_freight/parse_create_bol_response_spec.rb
- spec/friendly_shipping/services/tforce_freight/rates_options_spec.rb
- spec/friendly_shipping/services/tforce_freight/rates_package_options_spec.rb
- spec/friendly_shipping/services/tforce_freight_spec.rb
TForce (formerly UPS Freight) is building [a new API](https://developer.tforcefreight.com/) distinct from UPS. This PR implements the [Create BOL](https://developer.tforcefreight.com/api-details#api=shipping-cie-vnext&operation=shipping-create-bol) call.
> Add TForce create BOL service method

- lib/friendly_shipping/services/ship_engine/serialize_address_validation_request.rb
- spec/cassettes/shipengine/validate_address/success.yml
- spec/friendly_shipping/services/ship_engine/serialize_address_validation_request_spec.rb
The API expects an array of hashes, we were just passing a single hash.
> Fix ShipEngine address validation serializer

- lib/friendly_shipping/services/ship_engine.rb
- lib/friendly_shipping/services/ship_engine/parse_address_validation_response.rb
- spec/friendly_shipping/services/ship_engine/parse_address_validation_response_spec.rb
This updates the return value from the ShipEngine `#validate_address` method to be an array of locations instead of just a single location. The API is capable of validating multiple addresses at the same time, and we should be consistent with our other service classes which also return an array of locations when validating addresses.
> Fix ShipEngine address validation return value

- lib/friendly_shipping/services/ship_engine/parse_rate_estimates_response.rb
- lib/friendly_shipping/services/ship_engine/parse_rates_response.rb
- spec/friendly_shipping/services/ship_engine/parse_rate_estimates_response_spec.rb
- spec/friendly_shipping/services/ship_engine/parse_rates_response_spec.rb
This adds additional data to rates returned by ShipEngine. These values are specific to ShipEngine and as such are added to the `data` hash on each returned `Rate` object.
> Add additional response data to ShipEngine rates

- lib/friendly_shipping/services/ship_engine/serialize_rate_estimate_request.rb
- spec/friendly_shipping/services/ship_engine/serialize_rate_estimate_request_spec.rb
Instead of passing length/width/height of zero to ShipEngine's rate estimates API endpoint, let's just exclude the dimensions entirely. They aren't required for this API call anyway.
> Exclude dimensions from ShipEngine rate estimates when zero

- lib/friendly_shipping/services/ship_engine/rates_options.rb
- lib/friendly_shipping/services/ship_engine/serialize_address_residential_indicator.rb
- lib/friendly_shipping/services/ship_engine/serialize_rates_request.rb
- spec/friendly_shipping/services/ship_engine/rates_options_spec.rb
- spec/friendly_shipping/services/ship_engine/serialize_rates_request_spec.rb
When `comparison_rate_type` is set to "retail" ShipEngine returns retail rates (instead of commercial rates) from the rates API endpoint. Note that this only works for UPS/USPS carriers.
> Add `comparison_rate_type` to ShipEngine rates requests

- lib/friendly_shipping/carrier.rb
- lib/friendly_shipping/services/ship_engine/rate_estimates_options.rb
- lib/friendly_shipping/services/ship_engine/rates_options.rb
There was some confusion surrounding the `ship_date` attribute. Was it a date or a time? This clarifies that it can be anything as long as it responds to the `#strftime` method.
Also took the opportunity to clean up and finish the YARD docs for these 2 options classes.
> Fix YARD docs for ShipEngine rates options

- lib/friendly_shipping/services/rl/serialize_location.rb
- spec/friendly_shipping/services/rl/serialize_location_spec.rb
R+L does not accept periods in city names. We need to remove them before sending requests containing addresses.
> Remove periods from city names for R+L requests

- lib/friendly_shipping/services/tforce_freight/generate_handling_units_hash.rb
- lib/friendly_shipping/services/tforce_freight/structure_options.rb
- lib/friendly_shipping/services/ups_freight/generate_handling_units_hash.rb
- lib/friendly_shipping/services/ups_freight/rates_structure_options.rb
- spec/friendly_shipping/services/tforce_freight/generate_handling_units_hash_spec.rb
- spec/friendly_shipping/services/tforce_freight/structure_options_spec.rb
- spec/friendly_shipping/services/ups_freight/generate_handling_units_hash_spec.rb
Updates the TForce `GenerateHandlingUnitsHash` class to use structures instead of packages. This was overlooked during the [recent updates](https://github.com/friendlycart/friendly_shipping/pull/201) of our Freight service classes to use structures (pallets) and packages.
> Update TForce handling units class to use structures instead of packages

- lib/friendly_shipping/services/ups/shipping_methods.rb
Poland's ISO code is PL, not PO. This error leads to a country being `nil`, and further errors.
> Fix Poland's ISO code

- lib/friendly_shipping/services/rl/bol_options.rb
- lib/friendly_shipping/services/rl/rate_quote_options.rb
- lib/friendly_shipping/services/rl/shipment_options.rb
- lib/friendly_shipping/services/ship_engine_ltl/quote_options.rb
This cleans up some deprecation warnings that were duplicating warnings elsewhere in the code.
For example, we were checking `if options.package_options` in some places and warning about deprecations if the options existed, but this would also trigger the warning within the `#package_options` method itself which was unnecessary.
> Remove duplicate package deprecation warnings

- lib/friendly_shipping/services/usps/rate_estimate_package_options.rb
- lib/friendly_shipping/services/usps/serialize_rate_request.rb
- lib/friendly_shipping/services/usps/shipping_methods.rb
- spec/friendly_shipping/services/usps/rate_estimate_package_options_spec.rb
- spec/friendly_shipping/services/usps/serialize_rate_request_spec.rb
The USPS API replaced First Class package mail types with Ground Advantage last year. This commit marks the deprecated package mail types and shows a warning if/when they get used.
> Deprecate legacy First Class mail types

- lib/friendly_shipping/services/ups_json/generate_labels_payload.rb
- lib/friendly_shipping/services/ups_json/generate_package_hash.rb
This was overlooked in the initial implementation. These appear at the bottom of the label.
> Add reference numbers to packages

- lib/friendly_shipping/services/ups_json/parse_json_response.rb
- spec/cassettes/ups_json/labels/malformed.yml
- spec/friendly_shipping/services/ups_json_spec.rb
UPS unfortunately likes to return http success codes on failures. They also will sometimes return invalid json on these "successes". In those cases, prefer to use the error description header which has been seen to be more descriptive.
> Use error description when UPS returns bad json

- lib/friendly_shipping/services/tforce_freight/parse_create_bol_response.rb
- lib/friendly_shipping/services/tforce_freight/shipment_information.rb
- spec/fixtures/tforce_freight/create_bol/success.json
- spec/friendly_shipping/services/tforce_freight/parse_create_bol_response_spec.rb
- spec/friendly_shipping/services/tforce_freight/shipment_information_spec.rb
Capturing these numbers is helpful when a pickup request needs to be cancelled.
> TForce Freight: Parse pickup confirmation numbers

- lib/friendly_shipping/services/tforce_freight/document_options.rb
- lib/friendly_shipping/services/tforce_freight/generate_document_options_hash.rb
- spec/friendly_shipping/services/tforce_freight/document_options_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_create_bol_request_hash_spec.rb
- spec/friendly_shipping/services/tforce_freight/generate_document_options_hash_spec.rb
The old TForce (UPS) API used 2 codes to determine whether the shipping label was thermal or not. The new TForce API uses a wide variety of label type codes for different label sizes and formats. This commit adds the new codes to the document options class and deprecates the old `thermal` attribute.
> Fix TForce shipping label codes

- .env.template
- .env.test.local.template
- .gitignore
- spec/friendly_shipping/services/tforce_freight_spec.rb
This does a few things:
- Adds `.env.test.local` to `.gitignore`
- Adds `.env.test.local.template` with example `ACCESS_KEY` entry
- Updates TForce specs to reference `ACCESS_KEY`
The idea is to make it easy to re-record VCR cassettes for service class specs without having to hard-code access tokens in the specs themselves. Instead, the access token can be added to `.env.local.test` without risk of accidentally committing a sensitive value to the repository.
> Add `.env.test.local.template` file

- lib/friendly_shipping/services/ups_json/api_error.rb
- spec/cassettes/ups_json/labels/city_name.yml
- spec/friendly_shipping/services/ups_json_spec.rb
The default error handler would return "400 Bad Request" which is not very helpful to the humans who see it. The error description in the header points the user the real problem.
> Better error message on 400 from UPS json api

- lib/friendly_shipping/services/tforce_freight/generate_create_bol_request_hash.rb
- spec/friendly_shipping/services/tforce_freight/generate_create_bol_request_hash_spec.rb
TForce sets limits on certain values. This commit truncates the values to ensure we don't get error responses from the API.
> Truncate long values in TForce API requests

- lib/friendly_shipping/services/tforce_freight/generate_create_bol_request_hash.rb
- spec/friendly_shipping/services/tforce_freight/generate_create_bol_request_hash_spec.rb
TForce does not like certain chars like ampersands in company names. This commit replaces these chars with HTML entities which appear as expected on the resulting Bill of Lading (BOL).
> Escape special chars in TForce BOL API request

- lib/friendly_shipping/services/usps_ship/rate_estimate_package_options.rb
- spec/friendly_shipping/services/usps_ship/rate_estimate_package_options_spec.rb
- spec/friendly_shipping/services/usps_ship/serialize_rate_estimates_request_spec.rb
This changes the default value for rate indicator from "DP" (dimensional rate) to "SP" (single piece). The reasoning behind this change is that far more packages qualify as single piece vs. dimensional.
> Change USPS Ship package option default value

- lib/friendly_shipping/services/usps_ship/machinable_package.rb
- spec/friendly_shipping/services/usps_ship/machinable_package_spec.rb
During the transition to the new USPS Ship API, I noticed the machinable criteria has changed (either that or our criteria was wrong to begin with). This adjusts the dimensions and adds a min weight per section 7.5 here:
https://pe.usps.com/text/dmm300/201.htm#ep1097220
> USPS Ship: Fix machinable criteria

- lib/friendly_shipping/services/ship_engine.rb
- spec/friendly_shipping/services/ship_engine_spec.rb
This was overlooked in the original implementation. The other service methods already have debug params. Only `#labels` needs one. Setting `debug: true` causes the API request and response to be included with the API result.
> Add debug param to ShipEngine labels method

- lib/friendly_shipping/services/rl/serialize_location.rb
- spec/friendly_shipping/services/rl/serialize_location_spec.rb
R+L does not accept values over 30 chars.
> Truncate R+L BOL address lines to 30 chars

- lib/friendly_shipping/services/ups_json/parse_rate_modifier_hash.rb
- lib/friendly_shipping/services/ups_json/parse_rates_response.rb
- spec/fixtures/ups_json/rates_with_negotiated_charges.json
- spec/fixtures/ups_json/rates_with_rate_modifiers.json
- spec/fixtures/ups_json/ups_rates_canadian.json
- spec/friendly_shipping/services/ups_json/parse_rates_response_spec.rb
There were a bunch of problems with the extra data being returned with the rates response. This is not too surprising given that only the top level rate costs were the only thing covered by tests.
I am not a fan of the `[label, amount]` array that mostly acts like a hash but will clean that up later.
> Fix UPS json rate details, add specs

- lib/friendly_shipping/services/ups_json/parse_labels_response.rb
- lib/friendly_shipping/services/ups_json/parse_money_hash.rb
- spec/fixtures/ups_json/labels_two_packages.json
- spec/fixtures/ups_json/labels_with_negotiated_rates.json
- spec/friendly_shipping/services/ups_json/parse_labels_response_spec.rb
- spec/friendly_shipping/services/ups_json_spec.rb
The base service charge was not getting named correctly. Multiple charges in the same category were also getting dropped.
> Fix ups label cost breakdown

- .rubocop.yml
- lib/friendly_shipping/services/tforce_freight/generate_create_bol_request_hash.rb
- spec/friendly_shipping/services/tforce_freight/generate_create_bol_request_hash_spec.rb
We were escaping special characters like ampersands because the TForce API was returning server errors. They have since fixed the problem so the sanitization code can be safely removed.
> Remove TForce company name sanitization

- lib/friendly_shipping/services/ups_json/generate_rates_payload.rb
- spec/friendly_shipping/services/ups_json/generate_rates_payload_spec.rb
The `NegotiatedRatesIndicator` here must be submitted within `ShipmentRatingOptions` according to the UPS documentation:
[link to docs](https://developer.ups.com/api/reference?loc=en_US#operation/Rate!path=RateRequest/Shipment/ShipmentRatingOptions/NegotiatedRatesIndicator&t=request)
Similar to other `*Indicator` values for UPS Json, it also should be a `string`.
This is similar to how the option is handled for generating labels, which is already being set correctly:
https://github.com/friendlycart/friendly_shipping/blob/932e5a81d3a67f179c46f6ff556fdc960e6a3002/lib/friendly_shipping/services/ups_json/generate_labels_payload.rb#L59-L61
> Update payload location of NegotiatedRatesIndicator within UPS JSON

- friendly_shipping.gemspec
- lib/friendly_shipping/services/rl/parse_rate_quote_response.rb
- spec/friendly_shipping/services/rl/parse_rate_quote_response_spec.rb
The cost breakdown includes additional detail about the various rates and surcharges that makes up the total R+L rate.
> Attach cost breakdown to R+L rates data

- lib/friendly_shipping/services/rl/parse_rate_quote_response.rb
- lib/friendly_shipping/services/tforce_freight/parse_rates_response.rb
- spec/friendly_shipping/services/tforce_freight/parse_rates_response_spec.rb
Before, we were only returning the code and value for each charge returned in the TForce API response. Now we're returning the description and unit as well.
The charges have also been moved under their own `cost_breakdown` key.
> Expand TForce cost breakdown detail

- lib/friendly_shipping/services/ups_json/generate_rates_payload.rb
- spec/friendly_shipping/services/ups_json/generate_rates_payload_spec.rb
This fixes a bug when the UPS rates option `negotiated_rates` flag is set to false. The `ShipmentRatingOptions` value ends up being an empty hash. The UPS API used to tolerate this just fine, but in a recent update they began complaining with an error response like this:
`Atleast one shipment rating option either negotiated or FRS rates or ratechart indicator is required.`
This changes the rates payload generator to leave out the `ShipmentRatingOptions` key when `negotiated_rates` is false.
> Never send empty UPS `ShipmentRatingOptions`

- lib/friendly_shipping/services/ups_json.rb
- lib/friendly_shipping/services/ups_json/generate_city_state_lookup_payload.rb
- lib/friendly_shipping/services/ups_json/parse_city_state_lookup_response.rb
- spec/cassettes/ups_json/city_state_lookup/known_zip.yml
- spec/cassettes/ups_json/city_state_lookup/unknown_zip.yml
- spec/fixtures/ups_json/city_state_lookup.json
- spec/friendly_shipping/services/ups_json/generate_city_state_lookup_payload_spec.rb
- spec/friendly_shipping/services/ups_json/parse_city_state_lookup_response_spec.rb
- spec/friendly_shipping/services/ups_json_spec.rb
Given a zip code, this endpoint can be used to look up the city and state associated with that zip code.
> Add city/state lookup endpoint for UPS JSON API

- lib/friendly_shipping.rb
- lib/friendly_shipping/access_token.rb
- lib/friendly_shipping/services/tforce_freight/access_token.rb
- lib/friendly_shipping/services/ups_json/access_token.rb
- lib/friendly_shipping/services/usps_ship/access_token.rb
- spec/friendly_shipping/services/usps/choose_package_rate_spec.rb
- spec/friendly_shipping/services/usps/rate_estimate_package_options_spec.rb
- spec/support/shared_examples/overrideable_package_options_class.rb
- spec/support/shared_examples/overrideable_structure_options_class.rb
This DRYs up the carrier-specific access token classes.
> Extract `AccessToken` parent class

- lib/friendly_shipping/api_error.rb
- lib/friendly_shipping/services/ups_json/parse_json_response.rb
- lib/friendly_shipping/services/usps_ship/parse_timings_response.rb
- spec/friendly_shipping/api_error_spec.rb
- spec/friendly_shipping/services/ups_json/parse_json_response_spec.rb
- spec/friendly_shipping/services/usps_ship/parse_timings_response_spec.rb
This makes the error response a bit more uniform. Where CandleScience handles these failures, we expect ApiFailures to wrap an exception, but in several cases its just a string. This was resulting in some errors not being reported to our bug tracking service.
> Return errors in ApiFailures for USPS timings, UPS json parsing

- Gemfile
As of Ruby 3.4, observer is no longer included in the standard library.
> Add observer gem to Gemfile
