lib/friendly_shipping/version.rb

This includes a fix for USPS First Class commercial shipments, and adds
rate quoting.

Minor version bump to 0.2.3

---

lib/friendly_shipping/services/usps.rb
lib/friendly_shipping/services/usps/parse_address_validation_response.rb
lib/friendly_shipping/services/usps/parse_city_state_lookup_response.rb
lib/friendly_shipping/services/usps/parse_xml_response.rb
lib/friendly_shipping/services/usps/serialize_address_validation_request.rb
lib/friendly_shipping/services/usps/serialize_city_state_lookup_request.rb
spec/cassettes/usps/address_validation/correctable_address.yml
spec/cassettes/usps/address_validation/incomplete_address.yml
spec/cassettes/usps/address_validation/invalid_address.yml
spec/cassettes/usps/address_validation/valid_address.yml
spec/cassettes/usps/city_state_lookup/failure.yml
spec/cassettes/usps/city_state_lookup/multiple_states.yml
spec/cassettes/usps/city_state_lookup/success.yml
spec/fixtures/usps/address_validation_no_candidates_response.xml
spec/fixtures/usps/address_validation_response.xml
spec/fixtures/usps/city_state_lookup_response.xml
spec/friendly_shipping/services/usps/parse_address_validation_response_spec.rb
spec/friendly_shipping/services/usps/parse_city_state_lookup_response_spec.rb
spec/friendly_shipping/services/usps/serialize_address_validation_request_spec.rb
spec/friendly_shipping/services/usps/serialize_city_state_lookup_request_spec.rb
spec/friendly_shipping/services/usps_spec.rb

This adds address validation using the USPS service, analogous to the UPS service as in #21

Add USPS address validation and city/state lookup

---

lib/friendly_shipping/version.rb

We should bump the version to reflect API changes.

Bump version

---

lib/friendly_shipping/services/ship_engine.rb
lib/friendly_shipping/services/ship_engine/serialize_label_shipment.rb
spec/friendly_shipping/services/ship_engine/serialize_label_shipment_spec.rb

I'm at the end of my day here and don't have time to write a failing spec for this yet. @mamhoff could you handle adding a spec and getting this merged?

Fix wrong method call on SerializeLabelShipment

---

lib/friendly_shipping/api_failure.rb
lib/friendly_shipping/api_result.rb
lib/friendly_shipping/carrier.rb
lib/friendly_shipping/http_client.rb
lib/friendly_shipping/label.rb
lib/friendly_shipping/rate.rb
lib/friendly_shipping/request.rb
lib/friendly_shipping/response.rb
lib/friendly_shipping/shipping_method.rb
spec/friendly_shipping/carrier_spec.rb
spec/friendly_shipping/http_client_spec.rb
spec/friendly_shipping/label_spec.rb
spec/friendly_shipping/rate_spec.rb
spec/friendly_shipping/response_spec.rb
spec/friendly_shipping/services/ship_engine/parse_rate_estimate_response_spec.rb
spec/friendly_shipping/shipping_method_spec.rb

I was unsure about some of these types so please let me know if anything is wrong.

Add documentation to model initializers

---

lib/friendly_shipping/services/usps/serialize_rate_request.rb
spec/cassettes/ups/address_classification/commercial_address.yml
spec/cassettes/ups/address_classification/residential_address.yml
spec/cassettes/ups/address_classification/unknown_address.yml
spec/friendly_shipping/services/ups/label_item_options_spec.rb
spec/friendly_shipping/services/ups/serialize_package_node_spec.rb
spec/friendly_shipping/services/ups/serialize_rating_service_selection_request_spec.rb
spec/friendly_shipping/services/ups_spec.rb
spec/friendly_shipping/services/usps/choose_package_rate_spec.rb
spec/friendly_shipping/services/usps/serialize_rate_request_spec.rb
spec/spec_helper.rb

Adds some missing specs to improve code coverage.

Boost code coverage

---

lib/friendly_shipping/package_options.rb
lib/friendly_shipping/shipment_options.rb

It turns out this introduces a lot of complexity that does not seem to
be necessary for implementing even pretty complex APIs.

Remove Options Finder Arguments

---

README.md
lib/friendly_shipping/services/ups_freight.rb
lib/friendly_shipping/services/ups_freight/generate_commodity_information.rb
lib/friendly_shipping/services/ups_freight/generate_freight_rate_request_hash.rb
lib/friendly_shipping/services/ups_freight/generate_location_hash.rb
lib/friendly_shipping/services/ups_freight/generate_ups_security_hash.rb
lib/friendly_shipping/services/ups_freight/parse_freight_rate_response.rb
lib/friendly_shipping/services/ups_freight/parse_json_response.rb
lib/friendly_shipping/services/ups_freight/rates_item_options.rb
lib/friendly_shipping/services/ups_freight/rates_options.rb
lib/friendly_shipping/services/ups_freight/rates_package_options.rb
lib/friendly_shipping/services/ups_freight/shipping_methods.rb
spec/cassettes/ups_freight/labels/success.yml
spec/fixtures/ups_freight/rate_estimates/failure.json
spec/fixtures/ups_freight/rate_estimates/success.json
spec/friendly_shipping/services/ups_freight/generate_freight_rate_request_hash_spec.rb
spec/friendly_shipping/services/ups_freight/generate_location_hash_spec.rb
spec/friendly_shipping/services/ups_freight/generate_ups_security_hash_spec.rb
spec/friendly_shipping/services/ups_freight/parse_freight_rate_response_spec.rb
spec/friendly_shipping/services/ups_freight/parse_json_response_spec.rb
spec/friendly_shipping/services/ups_freight/rates_item_options_spec.rb
spec/friendly_shipping/services/ups_freight/rates_options_spec.rb
spec/friendly_shipping/services/ups_freight/rates_package_options_spec.rb
spec/friendly_shipping/services/ups_freight_spec.rb

This adds UPS Freight Rate quoting.

UPS Freight Rate Quoting

---

CHANGELOG.md
README.md
lib/friendly_shipping/services/ups_freight/rates_options.rb
lib/friendly_shipping/version.rb

Adapts the README and some changelog stuff (the dates were all wrong).

Move to 0.4.0

---

CHANGELOG.md
lib/friendly_shipping/services/ups.rb
lib/friendly_shipping/services/ups/parse_void_shipment_response.rb
lib/friendly_shipping/services/ups/serialize_void_shipment_request.rb
lib/friendly_shipping/version.rb
spec/cassettes/ups/void/failure.yml
spec/cassettes/ups/void/success.yml
spec/fixtures/ups/void_shipment_response.xml
spec/friendly_shipping/services/ups/parse_void_shipment_response_spec.rb
spec/friendly_shipping/services/ups/serialize_void_shipment_request_spec.rb
spec/friendly_shipping/services/ups_spec.rb

This adds support for voiding UPS labels. Pretty simple API call :)

Support for voiding UPS labels

---

lib/friendly_shipping/services/usps.rb
lib/friendly_shipping/services/usps/parse_time_in_transit_response.rb
lib/friendly_shipping/services/usps/serialize_time_in_transit_request.rb
lib/friendly_shipping/services/usps/timing_options.rb
lib/friendly_shipping/timing.rb
spec/cassettes/usps/timings/failure.yml
spec/cassettes/usps/timings/success.yml
spec/fixtures/usps/time_in_transit_response.xml
spec/friendly_shipping/services/usps/parse_time_in_transit_response_spec.rb
spec/friendly_shipping/services/usps/serialize_time_in_transit_request_spec.rb
spec/friendly_shipping/services/usps/timing_options_spec.rb
spec/friendly_shipping/services/usps_spec.rb
spec/friendly_shipping/timing_spec.rb

This implements the USPS time-in-transit API request. Interestingly, USPS' response has different XML schemas for expedited vs. non-expedited shipping methods. You'll see in 50e400b how that plays out. :)

USPS transit timings

---

CHANGELOG.md
lib/friendly_shipping/version.rb

This adds recent improvements to a new release.

Bump version, add 0.4.7 changelog

---

lib/friendly_shipping/services/usps/parse_time_in_transit_response.rb
spec/fixtures/usps/time_in_transit_response_without_expedited.xml
spec/friendly_shipping/services/usps/parse_time_in_transit_response_spec.rb

Sometimes, USPS will not return any expedited nodes. In this case,
finding the EAD will break. This commit makes sure we exit early if no
expedited nodes are found.

Return early if no expedited nodes in USPS response

---

.rubocop-relaxed.yml

Fix Namespace of LineLength Rubocop

---

lib/friendly_shipping/services/ups/parse_rate_response.rb
spec/friendly_shipping/services/ups/parse_rate_response_spec.rb

This adds package-level detail to the UPS rates. Self explanatory.

Add package-level detail to UPS rates

---

CHANGELOG.md
lib/friendly_shipping/version.rb

Run-up to a new release with an important bug fix and new features

Bump version to 0.4.9, log changes

---

CHANGELOG.md
lib/friendly_shipping/version.rb

Bump to 0.4.10, log changes

---

CHANGELOG.md
lib/friendly_shipping/version.rb

A new version with more USPS fixes.

Bump version to 0.4.11, log changes

---

CHANGELOG.md
lib/friendly_shipping/version.rb

We need a new release cut for 0.4.12.

Bump version to 0.4.12, log changes

---

lib/friendly_shipping/services/usps/serialize_rate_request.rb

Fix rate request serializer docs

---

lib/friendly_shipping/services/ups.rb
lib/friendly_shipping/services/usps/rate_estimate_options.rb
lib/friendly_shipping/services/usps/serialize_rate_request.rb

Misc documentation fixes

---

friendly_shipping.gemspec

Fix homepage link in gemspec

---

CHANGELOG.md
friendly_shipping.gemspec
lib/friendly_shipping/version.rb

Also adds in a recommended security fix in our development dependencies.

Release 0.6.1

---

CHANGELOG.md
lib/friendly_shipping/version.rb

Release 0.6.3 with some additions and changes.

Bump version and update changelog

---

.env.template
README.md
lib/friendly_shipping/services/ship_engine.rb

Fixes a few ShipEngine typos

---

lib/friendly_shipping/services/ups_freight/generate_delivery_options_hash.rb
lib/friendly_shipping/services/ups_freight/generate_pickup_options_hash.rb
lib/friendly_shipping/services/ups_freight/label_delivery_options.rb
lib/friendly_shipping/services/ups_freight/label_pickup_options.rb
spec/friendly_shipping/services/ups_freight/label_delivery_options_spec.rb
spec/friendly_shipping/services/ups_freight/label_pickup_options_spec.rb

This adds more pickup and delivery options supported by the TForce/UPS Freight API.

More Freight pickup and delivery options

---

friendly_shipping.gemspec
lib/friendly_shipping/services/ups/rate_estimate_options.rb
lib/friendly_shipping/services/ups/rate_estimate_package_options.rb
lib/friendly_shipping/services/ups_freight/label_options.rb
lib/friendly_shipping/services/usps/rate_estimate_options.rb
lib/friendly_shipping/services/usps/rate_estimate_package_options.rb
spec/friendly_shipping/services/usps/choose_package_rate_spec.rb
spec/spec_helper.rb

Fixes keyword args for Ruby 3. Also updates the `physical` gem version.

Ruby 3 support

---

lib/friendly_shipping.rb
lib/friendly_shipping/package_options.rb
lib/friendly_shipping/services/usps/rate_estimate_package_options.rb
lib/friendly_shipping/services/usps_international.rb
lib/friendly_shipping/services/usps_international/parse_package_rate.rb
lib/friendly_shipping/services/usps_international/parse_rate_response.rb
lib/friendly_shipping/services/usps_international/rate_estimate_options.rb
lib/friendly_shipping/services/usps_international/rate_estimate_package_options.rb
lib/friendly_shipping/services/usps_international/serialize_rate_request.rb
lib/friendly_shipping/services/usps_international/shipping_methods.rb
spec/cassettes/usps_international/rate_estimates/success.yml
spec/fixtures/usps_international/rates_api_response.xml
spec/friendly_shipping/services/usps_international/parse_package_rate_spec.rb
spec/friendly_shipping/services/usps_international/parse_rate_response_spec.rb
spec/friendly_shipping/services/usps_international/rate_estimate_package_options_spec.rb
spec/friendly_shipping/services/usps_international/rate_estimates_options_spec.rb
spec/friendly_shipping/services/usps_international/serialize_rate_request_spec.rb
spec/friendly_shipping/services/usps_international_spec.rb
spec/spec_helper.rb

USPS International
Add support for requesting rate estimates for USPS International packages

USPS International Rates

---

lib/friendly_shipping.rb
lib/friendly_shipping/http_client.rb
lib/friendly_shipping/inflections.rb
lib/friendly_shipping/services/rl.rb
lib/friendly_shipping/services/rl/bad_request.rb
lib/friendly_shipping/services/rl/bad_request_handler.rb
lib/friendly_shipping/services/rl/item_options.rb
lib/friendly_shipping/services/rl/package_options.rb
lib/friendly_shipping/services/rl/parse_rate_quote_response.rb
lib/friendly_shipping/services/rl/parse_transit_times_response.rb
lib/friendly_shipping/services/rl/rate_quote_options.rb
lib/friendly_shipping/services/rl/serialize_rate_quote_request.rb
lib/friendly_shipping/services/rl/serialize_transit_times_request.rb
lib/friendly_shipping/services/rl/shipping_methods.rb
spec/cassettes/rl/rate_quote/failure.yml
spec/cassettes/rl/rate_quote/success.yml
spec/cassettes/rl/transit_times/failure.yml
spec/cassettes/rl/transit_times/success.yml
spec/fixtures/rl/item_required.json
spec/fixtures/rl/rate_quotes.json
spec/fixtures/rl/transit_timings.json
spec/fixtures/rl/zip_required.json
spec/friendly_shipping/services/rl/item_options_spec.rb
spec/friendly_shipping/services/rl/parse_rate_quote_response_spec.rb
spec/friendly_shipping/services/rl/parse_transit_times_response_spec.rb
spec/friendly_shipping/services/rl/rate_quote_options_spec.rb
spec/friendly_shipping/services/rl/serialize_rate_quote_request_spec.rb
spec/friendly_shipping/services/rl/serialize_transit_times_request_spec.rb
spec/friendly_shipping/services/rl_spec.rb
spec/spec_helper.rb

This implements basic rate quotes and transit times against the R&L API.

Implement R&L service with rates and timings

---

lib/friendly_shipping/inflections.rb
lib/friendly_shipping/services/rl.rb
lib/friendly_shipping/services/rl/bill_of_lading_options.rb
lib/friendly_shipping/services/rl/item_options.rb
lib/friendly_shipping/services/rl/parse_create_bol_response.rb
lib/friendly_shipping/services/rl/pickup_request.rb
lib/friendly_shipping/services/rl/serialize_create_bol_request.rb
spec/cassettes/rl/create_bill_of_lading/failure.yml
spec/cassettes/rl/create_bill_of_lading/success.yml
spec/fixtures/rl/create_bol/failure.json
spec/fixtures/rl/create_bol/success.json
spec/friendly_shipping/services/rl/bill_of_lading_options_spec.rb
spec/friendly_shipping/services/rl/item_options_spec.rb
spec/friendly_shipping/services/rl/parse_create_bol_response_spec.rb
spec/friendly_shipping/services/rl/pickup_request_spec.rb
spec/friendly_shipping/services/rl/serialize_create_bol_request_spec.rb
spec/friendly_shipping/services/rl_spec.rb

This does not return the binary BOL yet. It just creates it and returns a PRO number and pickup request number.

Add R&L Freight API call to create BOL and schedule pickup

---

lib/friendly_shipping/services/rl/bol_options.rb
lib/friendly_shipping/services/rl/serialize_create_bol_request.rb
spec/friendly_shipping/services/rl/bol_options_spec.rb
spec/friendly_shipping/services/rl/serialize_create_bol_request_spec.rb

See https://technology.rlcarriers.com/api-documentation/bill-of-lading/

Add additional instructions to R+L BOL requests

---

lib/friendly_shipping/services/rl/bol_options.rb
lib/friendly_shipping/services/rl/serialize_create_bol_request.rb
spec/friendly_shipping/services/rl/bol_options_spec.rb
spec/friendly_shipping/services/rl/serialize_create_bol_request_spec.rb

See https://technology.rlcarriers.com/api-documentation/bill-of-lading/

Add special instructions to R+L BOL requests

---

lib/friendly_shipping/services/ups_freight/generate_freight_rate_request_hash.rb
lib/friendly_shipping/services/ups_freight/generate_freight_ship_request_hash.rb
lib/friendly_shipping/services/ups_freight/generate_handling_units_hash.rb
spec/friendly_shipping/services/ups_freight/generate_commodity_information_spec.rb
spec/friendly_shipping/services/ups_freight/generate_handling_units_hash_spec.rb

This abstracts generation of the handling units hashes for UPS Freight API requests.

Extract UPS Freight handling units generator class

---

lib/friendly_shipping/services/tforce_freight/rates_options.rb

This adds clarifying comments to the TForce Freight rating call type codes.

Add comments to TForce rating call type codes

---

lib/friendly_shipping/services/rl/parse_invoice_response.rb
spec/friendly_shipping/services/rl/parse_invoice_response_spec.rb

ShippingDocument changed to ShipmentDocument

Fix RL Invoice

---

lib/friendly_shipping/services/ups_json/parse_rates_response.rb
spec/friendly_shipping/services/ups_json_spec.rb

Fixes a few spec failures. Trying to get the suite green again.

Fix UPS JSON spec failures

---

lib/friendly_shipping/services/ship_engine.rb
lib/friendly_shipping/services/ship_engine/parse_address_validation_response.rb
lib/friendly_shipping/services/ship_engine/serialize_address_validation_request.rb
spec/cassettes/shipengine/validate_address/success.yml
spec/fixtures/ship_engine/address_validation_failure.json
spec/fixtures/ship_engine/address_validation_success.json
spec/friendly_shipping/services/ship_engine/parse_address_validation_response_spec.rb
spec/friendly_shipping/services/ship_engine/serialize_address_validation_request_spec.rb
spec/friendly_shipping/services/ship_engine_spec.rb

This implements a service method for ShipEngine's address validation API endpoint.

ShipEngine address validation service method

---

lib/friendly_shipping/services/usps_ship.rb
spec/friendly_shipping/services/usps_ship_spec.rb

When debug is enabled, we need to append the request/response to the summed API result for USPS Ship rate estimates.

Append request/response to USPS Ship API result
